# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1438, 754)
        self.background_label = QtWidgets.QLabel(Form)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 1438, 754))
        self.background_label.setStyleSheet("")
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap(":/newPrefix/template.png"))
        self.background_label.setScaledContents(True)
        self.background_label.setObjectName("background_label")
        self.today_png = QtWidgets.QLabel(Form)
        self.today_png.setGeometry(QtCore.QRect(340, 150, 231, 211))
        self.today_png.setText("")
        self.today_png.setPixmap(QtGui.QPixmap(":/newPrefix/weather_pngs/hot.png"))
        self.today_png.setScaledContents(True)
        self.today_png.setObjectName("today_png")
        self.gizli_label = QtWidgets.QLabel(Form)
        self.gizli_label.setGeometry(QtCore.QRect(860, 100,431,61))
        self.gizli_label.setText('')
        self.gizli_label.setStyleSheet('background-color:transparent;\ncolor:white')
        self.gizli_label.setAlignment(QtCore.Qt.AlignCenter)
        #67A5BB
        font = QtGui.QFont()
        font.setPointSize(25)
        self.gizli_label.setFont(font)
        self.today_day = QtWidgets.QLabel(Form)
        self.today_day.setGeometry(QtCore.QRect(110, 170, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(20)
        self.today_day.setFont(font)
        self.today_day.setStyleSheet("color: rgb(255, 255, 255);")
        self.today_day.setObjectName("today_day")
        self.today_degree = QtWidgets.QLabel(Form)
        self.today_degree.setGeometry(QtCore.QRect(110, 220, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(49)
        font.setBold(False)
        font.setWeight(50)
        self.today_degree.setFont(font)
        self.today_degree.setStyleSheet("color: rgb(255, 255, 255);")
        self.today_degree.setObjectName("today_degree")
        self.location_label = QtWidgets.QLabel(Form)
        self.location_label.setGeometry(QtCore.QRect(110, 320, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(17)
        self.location_label.setFont(font)
        self.location_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.location_label.setObjectName("location_label")
        self.hide_label = QtWidgets.QLabel(Form)
        self.hide_label.setGeometry(QtCore.QRect(890, 220, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(49)
        font.setBold(False)
        font.setWeight(50)
        self.hide_label.setFont(font)
        self.hide_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.hide_label.setObjectName("tomorrow_degree")
        self.tomorrow_day = QtWidgets.QLabel(Form)
        self.tomorrow_day.setGeometry(QtCore.QRect(890, 170, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(20)
        self.tomorrow_day.setFont(font)
        self.tomorrow_day.setStyleSheet("color: rgb(255, 255, 255);")
        self.tomorrow_day.setObjectName("tomorrow_day")
        self.tomorrow_wind_km = QtWidgets.QLabel(Form)
        self.tomorrow_wind_km.setGeometry(QtCore.QRect(890, 320, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(20)
        self.tomorrow_wind_km.setFont(font)
        self.tomorrow_wind_km.setStyleSheet("color: rgb(255, 255, 255);")
        self.tomorrow_wind_km.setObjectName("tomorrow_wind_km")
        self.tomorrow_png = QtWidgets.QLabel(Form)
        self.tomorrow_png.setGeometry(QtCore.QRect(1120, 160, 231, 216))
        self.tomorrow_png.setText("")
        self.tomorrow_png.setPixmap(QtGui.QPixmap(":/newPrefix/weather_pngs/warm.png"))
        self.tomorrow_png.setScaledContents(True)
        self.tomorrow_png.setObjectName("tomorrow_png")
        self.sun_rise_label = QtWidgets.QLabel(Form)
        self.sun_rise_label.setGeometry(QtCore.QRect(1040, 460, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.sun_rise_label.setFont(font)
        self.sun_rise_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sun_rise_label.setObjectName("sun_rise_label")
        self.sunset_label = QtWidgets.QLabel(Form)
        self.sunset_label.setGeometry(QtCore.QRect(1040, 525, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.sunset_label.setFont(font)
        self.sunset_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sunset_label.setObjectName("sunset_label")
        self.tomorrow_weather_status = QtWidgets.QLabel(Form)
        self.tomorrow_weather_status.setGeometry(QtCore.QRect(1160, 587, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.tomorrow_weather_status.setFont(font)
        self.tomorrow_weather_status.setStyleSheet("color: rgb(255, 255, 255);")
        self.tomorrow_weather_status.setObjectName("tomorrow_weather_status")
        self.today_wind_km = QtWidgets.QLabel(Form)
        self.today_wind_km.setGeometry(QtCore.QRect(305, 462, 231, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.today_wind_km.setFont(font)
        self.today_wind_km.setStyleSheet("color: rgb(255, 255, 255);")
        self.today_wind_km.setObjectName("today_wind_km")
        self.today_date = QtWidgets.QLabel(Form)
        self.today_date.setGeometry(QtCore.QRect(210, 527, 341, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.today_date.setFont(font)
        self.today_date.setStyleSheet("color: rgb(255, 255, 255);")
        self.today_date.setObjectName("today_date")
        self.today_weather_status = QtWidgets.QLabel(Form)
        self.today_weather_status.setGeometry(QtCore.QRect(380, 590, 168, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.today_weather_status.setFont(font)
        self.today_weather_status.setStyleSheet("color: rgb(255, 255, 255);")
        self.today_weather_status.setObjectName("today_weather_status")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(975, 690, 164, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color:white;\n"
"    background-color: rgb(127, 157, 168);\n"
"}\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.goto_button = QtWidgets.QPushButton(Form)
        self.goto_button.setGeometry(QtCore.QRect(1150, 690, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.goto_button.setFont(font)
        self.goto_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goto_button.setStyleSheet("QPushButton{\n"
"    border:1px solid black;\n"
"    border-radius: 15px;\n"
"    color:white;\n"
"    background-color: rgb(103, 165, 187);\n"
"}\n"
"QPushButton:hover{\n"
"    border:1px solid black;\n"
"    border-radius: 15px;\n"
"    color:white;\n"
"    background-color: rgb(57, 92, 104);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    border:1px solid black;\n"
"    border-radius: 15px;\n"
"    color:white;\n"
"    background-color: rgb(82, 131, 148);\n"
"}")
        self.goto_button.setObjectName("goto_button")
        self.about_button = QtWidgets.QPushButton(Form)
        self.about_button.setGeometry(QtCore.QRect(100, 690, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Medi")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.about_button.setFont(font)
        self.about_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about_button.setStyleSheet("QPushButton{\n"
"    border:1px solid black;\n"
"    border-radius: 15px;\n"
"    color:white;\n"
"    background-color: rgb(103, 165, 187);\n"
"}\n"
"QPushButton:hover{\n"
"    border:1px solid black;\n"
"    border-radius: 15px;\n"
"    color:white;\n"
"    background-color: rgb(57, 92, 104);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    border:1px solid black;\n"
"    border-radius: 15px;\n"
"    color:white;\n"
"    background-color: rgb(82, 131, 148);\n"
"}\n"
"    ")
        self.about_button.setObjectName("about_button")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(760, 540, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Weather Application"))
        self.today_day.setText(_translate("Form", "0"))
        self.today_degree.setText(_translate("Form", "0° C"))
        self.location_label.setText(_translate("Form", "0"))
        self.hide_label.setText(_translate("Form", "0° C"))
        self.tomorrow_day.setText(_translate("Form", "0"))
        self.tomorrow_wind_km.setText(_translate("Form", "0.0 km/h"))
        self.sun_rise_label.setText(_translate("Form", "0"))
        self.sunset_label.setText(_translate("Form", "0"))
        self.tomorrow_weather_status.setText(_translate("Form", "0"))
        self.today_wind_km.setText(_translate("Form", "0"))
        self.today_date.setText(_translate("Form", "0"))
        self.today_weather_status.setText(_translate("Form", "0"))
        self.goto_button.setText(_translate("Form", "Go to"))
        self.about_button.setText(_translate("Form", "About Developer"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())